milestones/milestone-3/PracticeProject/PracticeProject/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PracticeProject.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Contact page.";

            return View();
        }
    }
}

milestones/milestone-3/PracticeProject/PracticeProject/Controllers/SupportTicketsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PracticeProject.Models;

namespace PracticeProject.Controllers
{
    public class SupportTicketsController : Controller
    {
        private PracticeProjectContext db = new PracticeProjectContext();

        // GET: SupportTickets
        public ActionResult Index()
        {
            var recent = db.SupportTickets
                  .OrderBy(b => b.TimeSubmited)
                  .ToList();
            return View(recent);
        }

        // GET: SupportTickets/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SupportTickets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TicketsID,FirstName,LastName,Email,ReportType,UMessage,TimeSubmited")] SupportTicket supportTicket)
        {
            if (ModelState.IsValid)
            {
                db.SupportTickets.Add(supportTicket);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }

            return View(supportTicket);
        }

        // GET: SupportTickets/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SupportTicket supportTicket = db.SupportTickets.Find(id);
            if (supportTicket == null)
            {
                return HttpNotFound();
            }
            return View(supportTicket);
        }

        // POST: SupportTickets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SupportTicket supportTicket = db.SupportTickets.Find(id);
            db.SupportTickets.Remove(supportTicket);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

milestones/milestone-3/PracticeProject/PracticeProject/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

milestones/milestone-3/PracticeProject/PracticeProject/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   @Html.ActionLink("Report Issue", "Create", "SupportTickets")<br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

milestones/milestone-3/PracticeProject/PracticeProject/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="row">
    <div class="col-md-4 sidebar">
        <div class="nav-tabs">
            <button class="btn btn-tab" onclick="tab('new')">New</button>
            <button class="btn btn-tab" onclick="tab('top')">Top</button>
            <button class="btn btn-tab" onclick="tab('rising')">Rising</button>
        </div>
        <div class="lists">
            <div id="new" class="tab">
                <h2>New</h2>
                <p>This is where a list of links to the most recent 10 discussions will go</p>
            </div>

            <div id="top" class="tab" style="display:none">
                <h2>Top</h2>
                <p>This is where a list of links to the top 10 most active discussions of the day will go</p>
            </div>

            <div id="rising" class="tab" style="display:none">
                <h2>Rising</h2>
                <p>This is where a list of links to the top 10 discussions within the last hour will go</p>
            </div>
        </div>
    </div>


    <div class="col-md-8">
        <h1>Jabberbox</h1>
        <h2>We are totally not Reddit</h2>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vestibulum eu dolor in maximus. Morbi eu venenatis odio. Vestibulum non imperdiet enim. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse porttitor a metus vulputate sodales. Nulla libero augue, commodo sed purus in, sollicitudin volutpat massa. Aenean egestas ultrices viverra. Praesent ut urna elementum, consectetur velit in, convallis tortor. Fusce tincidunt sit amet ex nec fermentum. Suspendisse tincidunt arcu risus, sed facilisis eros rhoncus vel. Fusce vel egestas sapien. Pellentesque eu feugiat ante. Duis at lobortis quam. Mauris molestie eros a pulvinar sagittis. Fusce pulvinar purus id sem auctor, sit amet luctus turpis sodales.
        </p>
        <p>
            Morbi a lorem finibus, congue massa sed, venenatis arcu. In gravida ac felis eget consectetur. Aliquam erat volutpat. Integer ac vulputate ex, et ultrices metus. Integer hendrerit orci at imperdiet fermentum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed auctor enim quis sodales mollis. Integer ullamcorper libero eu pharetra tristique.
        </p>
        <blockquote>
            Your news, your voice, your way!
        </blockquote>

        @using Microsoft.AspNet.Identity
        @if (!Request.IsAuthenticated)
        {
        <div class="btn-area">
                @Html.ActionLink("Register", "Register", "Account", null, new { @class = "bg-btn" })
                @Html.ActionLink("Login", "Login", "Account", null, new { @class = "bg-btn" })
        </div>
        }
    </div>
</div>

@section scripts{
    <script type="text/javascript" src="~/Scripts/script.js"></script>
}