milestones/milestone-3/PracticeProject/PracticeProject/Models/Discussion.cs
namespace PracticeProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Discussion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Discussion()
        {
            Comments = new HashSet<Comment>();
        }

        [Key]
        public int DiscussionsID { get; set; }

        [DisplayName("Post Number")]
        public int PostsID { get; set; }

        [DisplayName("Number of Likes")]
        public int Likes { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }

        public virtual Post Post { get; set; }
    }
}

milestones/milestone-3/PracticeProject/PracticeProject/Controllers/DiscussionsController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PracticeProject.Models;

namespace PracticeProject.Controllers
{
    public class DiscussionsController : Controller
    {
        private PracticeProjectContext db = new PracticeProjectContext();

        // GET: Discussions
        public ActionResult Index()
        {
            var discussions = db.Discussions.Include(d => d.Post);
            return View(discussions.ToList());
        }




        // added this to get data for discussions page and display it in user specified order
        [HttpGet]
        public ActionResult DiscussionContent( int? id, int? check)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // get post id of dicussion post.
            int postId = db.Discussions.Find(id).PostsID;

            // Get post title
            ViewBag.postTitle = db.Posts.Find(postId).Title;

            // Get post content
            ViewBag.postContent = db.Posts.Find(postId).PostContent;

            // Get post timestamp
            ViewBag.postTime = db.Posts.Find(postId).DateTimeOfPost;


            // Get user id for post
            int userId = db.Posts.Find(postId).UsersID;

            // Get user first name
            ViewBag.firstNameOfPoster = db.Users.Find(userId).FirstName;

            // Get user last name
            ViewBag.lastNameOfPoster = db.Users.Find(userId).LastName;

            IEnumerable<Comment> item;

            if (check == 1)
            {
                // get all comments associated with the specified discussion ID.
                item = db.Comments.Where(comment => comment.DiscussionsID == id)
                               .OrderByDescending(b => b.DateTimeOfCommentCreation)
                              .ToList().AsEnumerable();

            }
            else
            {
                // get all comments associated with the specified discussion ID.
                 item = db.Comments.Where(comment => comment.DiscussionsID == id)
                              .OrderBy(b => b.DateTimeOfCommentCreation)
                              .ToList().AsEnumerable();

            }


            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);

        }





        // GET: Discussions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Discussion discussion = db.Discussions.Find(id);
            if (discussion == null)
            {
                return HttpNotFound();
            }
            return View(discussion);
        }

        // GET: Discussions/Create
        public ActionResult Create()
        {
            ViewBag.PostsID = new SelectList(db.Posts, "PostsID", "Title");
            return View();
        }

        // POST: Discussions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DiscussionsID,PostsID,Likes")] Discussion discussion)
        {
            if (ModelState.IsValid)
            {
                db.Discussions.Add(discussion);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PostsID = new SelectList(db.Posts, "PostsID", "Title", discussion.PostsID);
            return View(discussion);
        }

        // GET: Discussions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Discussion discussion = db.Discussions.Find(id);
            if (discussion == null)
            {
                return HttpNotFound();
            }
            ViewBag.PostsID = new SelectList(db.Posts, "PostsID", "Title", discussion.PostsID);
            return View(discussion);
        }

        // POST: Discussions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DiscussionsID,PostsID,Likes")] Discussion discussion)
        {
            if (ModelState.IsValid)
            {
                db.Entry(discussion).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PostsID = new SelectList(db.Posts, "PostsID", "Title", discussion.PostsID);
            return View(discussion);
        }

        // GET: Discussions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Discussion discussion = db.Discussions.Find(id);
            if (discussion == null)
            {
                return HttpNotFound();
            }
            return View(discussion);
        }

        // POST: Discussions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Discussion discussion = db.Discussions.Find(id);
            db.Discussions.Remove(discussion);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

milestones/milestone-3/PracticeProject/PracticeProject/Views/Discussions/Create.cshtml
@model PracticeProject.Models.Discussion

@{
    ViewBag.Title = "Create";
}

<h2>Create a new discussion</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Discussion details</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PostsID, "PostsID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PostsID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PostsID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Likes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Likes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Likes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

milestones/milestone-3/PracticeProject/PracticeProject/Views/Discussions/Delete.cshtml
@model PracticeProject.Models.Discussion

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Discussion</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Post.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Post.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Likes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Likes)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

milestones/milestone-3/PracticeProject/PracticeProject/Views/Discussions/Details.cshtml
@model PracticeProject.Models.Discussion

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Discussion</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Post.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Post.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Likes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Likes)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.DiscussionsID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

milestones/milestone-3/PracticeProject/PracticeProject/Views/Discussions/DiscussionContent.cshtml
@model IEnumerable<PracticeProject.Models.Comment>

@{
    ViewBag.Title = "Discussion";
}

<h2>Discussion</h2>

@{
    var idOfDiscussion = Model.First().DiscussionsID;

}



<table class="table">
    <tr>
        <th>
            @*@Html.DisplayNameFor(model => model.Post.Title) *@


            <span style="font-weight:Bold;"> Topic: <br /></span>
            <span style="font-weight:Bold;"> @ViewBag.postTitle</span>

        </th>

    </tr>
    <tr>

        <th>
            @* @Html.DisplayNameFor(model => model.Likes) *@

            <span style="font-weight:Bold;"> @ViewBag.postContent</span>

        </th>
        <th>
            <span style="font-weight:normal;"> @ViewBag.firstNameOfPoster @ViewBag.lastNameOfPoster</span>
        </th>

        <th>
            <span style="font-weight:normal;"> @ViewBag.postTime</span>
        </th>



        <th></th>
    </tr>

    <tr>
        <th>
            <span style="font-weight:Bold;">Comments</span>
            &nbsp;
            &nbsp;
            @Html.ActionLink("Newest first", "DiscussionContent", "Discussions", new { id = idOfDiscussion, check = 1 }, null)
            &nbsp;
            &nbsp;
            @Html.ActionLink("Oldest first", "DiscussionContent", "Discussions", new { id = idOfDiscussion, check = 0 }, null)
        </th>
    </tr>


    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CommentContent)


            </td>

            <td>
                @Html.DisplayFor(modelItem => item.User.FirstName)
                @Html.DisplayFor(modelItem => item.User.LastName)

            </td>

            <td>
                @Html.DisplayFor(modelItem => item.DateTimeOfCommentCreation)

            </td>





        </tr>
    }

</table>

milestones/milestone-3/PracticeProject/PracticeProject/Views/Discussions/Edit.cshtml
@model PracticeProject.Models.Discussion

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Discussion</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DiscussionsID)

        <div class="form-group">
            @Html.LabelFor(model => model.PostsID, "PostsID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PostsID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PostsID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Likes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Likes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Likes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

milestones/milestone-3/PracticeProject/PracticeProject/Views/Discussions/Index.cshtml
@model IEnumerable<PracticeProject.Models.Discussion>

@{
    ViewBag.Title = "Index";
}

<h2>Discussions</h2>

@using Microsoft.AspNet.Identity
@if (Request.IsAuthenticated)
{
    <p>
        @Html.ActionLink("Create New Discussion", "Create")
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Post.Title) 
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Likes)
        </th>
        <th></th>
    </tr>


@foreach (var item in Model) {
    <tr>
        <td>
            @* @Html.DisplayFor(modelItem => item.Post.Title) *@

            @*Added this link to discussion content page.*@
            @Html.ActionLink(item.Post.Title, "DiscussionContent", "Discussions", new { id = item.DiscussionsID }, null)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Likes)
        </td>
        <td>
          @* @Html.ActionLink("Edit", "Edit", new { id=item.DiscussionsID })  *@
             @Html.ActionLink("View Discussion", "DiscussionContent", new { id=item.DiscussionsID }) 
          @* @Html.ActionLink("Delete", "Delete", new { id=item.DiscussionsID }) *@
        </td>
    </tr>
}

</table>